package com.example.healthfirst;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.Window;
import android.view.WindowManager;
import android.widget.ImageView;
import android.widget.TextView;

import java.util.HashMap;

public class MainActivity5 extends AppCompatActivity
{

    int[] vegimages =
            {
                    R.drawable.almond1,
                    R.drawable.apple2,
                    R.drawable.apricot1,
                    R.drawable.artichoke2,
                    R.drawable.arugula2,
                    R.drawable.avocado2,
                    R.drawable.banana2,
                    R.drawable.bananas1,
                    R.drawable.beet2,
                    R.drawable.bellpepper2,
                    R.drawable.bokchoy2,
                    R.drawable.broccoli2,
                    R.drawable.cabbage2,
                    R.drawable.carrot1,
                    R.drawable.cauliflower1,
                    R.drawable.cherry1,
                    R.drawable.chili2,
                    R.drawable.coconut1,
                    R.drawable.corn1,
                    R.drawable.cucumber1,
                    R.drawable.dragon1,
                    R.drawable.durian1,
                    R.drawable.eggplant1,
                    R.drawable.fig1,
                    R.drawable.garlic1,
                    R.drawable.ginger2,
                    R.drawable.ginkgo2,
                    R.drawable.grape1,
                    R.drawable.guava1,
                    R.drawable.kale2,
                    R.drawable.kiwi2,
                    R.drawable.leek2,
                    R.drawable.lemon2,
                    R.drawable.lettuce1,
                    R.drawable.macadamianut2,
                    R.drawable.mache2,
                    R.drawable.mango1,
                    R.drawable.milk2,
                    R.drawable.mushrooms1,
                    R.drawable.okra2,
                    R.drawable.olives2,
                    R.drawable.onion1,
                    R.drawable.orange2,
                    R.drawable.papaya1,
                    R.drawable.parsley2,
                    R.drawable.passion1,
                    R.drawable.peach1,
                    R.drawable.peanut2,
                    R.drawable.pear1,
                    R.drawable.peas1,
                    R.drawable.pepper2,
                    R.drawable.pineapple1,
                    R.drawable.plum1,
                    R.drawable.pomegranate1,
                    R.drawable.potato1,
                    R.drawable.pumpkin1,
                    R.drawable.radish1,
                    R.drawable.raspberry1,
                    R.drawable.spinach1,
                    R.drawable.star1,
                    R.drawable.strawberry1,
                    R.drawable.tomato1,
                    R.drawable.turnip1,
                    R.drawable.walnut2,
                    R.drawable.watercress2,
                    R.drawable.watermelon1,
            };

    String vegtitle[] =
            {
                    "Almond",
                    "Apple",
                    "Apricot",
                    "Artichoke",
                    "Arugula",
                    "Avocado",
                    "Banana flower",
                    "Banana",
                    "Beet",
                    "Bell Pepper",
                    "Bok choy",
                    "Broccoli",
                    "Cabbage",
                    "Carrot",
                    "Cauliflower",
                    "Cherry",
                    "Chili",
                    "Coconut",
                    "Corn",
                    "Cucumber",
                    "Dragon fruit",
                    "Durian",
                    "Eggplant",
                    "Fig",
                    "Garlic",
                    "Ginger",
                    "Ginkgo",
                    "Grapes",
                    "Guava",
                    "Kale",
                    "Kiwi",
                    "Leek",
                    "Lemon",
                    "Lettuce",
                    "Macadamia nut",
                    "Mache",
                    "Mango",
                    "Milk",
                    "Mushroom",
                    "Okra",
                    "Olives",
                    "Onion",
                    "Orange",
                    "Papaya",
                    "Parsley",
                    "Passion fruit",
                    "Peach",
                    "Peanut",
                    "Pear",
                    "Peas",
                    "Pepper",
                    "Pineapple",
                    "Plum",
                    "Pomegranate",
                    "Potato",
                    "Pumpkin",
                    "Radish",
                    "Raspberry",
                    "Spinach",
                    "Starfruit",
                    "Strawberry",
                    "Tomato",
                    "Turnip",
                    "Walnut",
                    "Water cress",
                    "Watermelon",
            };

    //the info in the array will be changed later once we display info some info in our activity
    String vegdescription[] =
            {
                    "Almonds are the edible seeds of Prunus dulcis, more commonly called the almond tree. They are native to the Middle East, but the US is now the world's largest producer. The almonds you can buy in stores usually have the shell removed, revealing the edible nut inside. They are sold either raw or roasted",
                    "An apple is an edible fruit produced by an apple tree. Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus. The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found today",
                    "An apricot is a fruit, or the tree that bears the fruit, of several species in the genus Prunus. Usually, an apricot is from the species P. armeniaca, but the fruits of the other species in Prunus sect. Armeniaca are also called apricots.",
                    "The globe artichoke, also known by the names French artichoke and green artichoke in the U.S., is a variety of a species of thistle cultivated as a food. The edible portion of the plant consists of the flower buds before the flowers come into bloom.",
                    "Rocket or arugula is an edible annual plant in the family Brassicaceae used as a leaf vegetable for its fresh, tart, bitter, and peppery flavor. Other common names include garden rocket, and eruca. It is also called \"ruchetta\", \"rucola\", \"rucoli\", \"rugula\", \"colewort\", and \"roquette\"",
                    "The avocado, a tree likely originating from south-central Mexico, is classified as a member of the flowering plant family Lauraceae. The fruit of the plant, also called an avocado, is botanically a large berry containing a single large seed.",
                    "Banana flower, also known as banana blossom, is a tear-shaped maroon or purplish flower hanging at the end of banana clusters grows on the end of the stem holding a cluster of bananas. The edible flower has a unique and excellent taste rich in nutrients.",
                    "A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. In some countries, bananas used for cooking may be called plantains, distinguishing them from dessert bananas.",
                    "The beetroot is the taproot portion of a beet plant, usually known in Canada and the USA as beets while the vegetable is referred to as beetroot in British English, and also known as the table beet, garden beet, red beet, dinner beet or golden beet.",
                    "The bell pepper is the fruit of plants in the Grossum cultivar group of the species Capsicum annuum. Cultivars of the plant produce fruits in different colors, including red, yellow, orange, green, white, and purple. Bell peppers are sometimes grouped with less pungent pepper varieties as sweet peppers.",
                    "Bok choy, pak choi, pichaypetsay, or pok choi is a type of Chinese cabbage. Chinensis varieties do not form heads and have green leaf blades with lighter bulbous bottoms instead, forming a cluster reminiscent of mustard greens. Chinensis varieties are popular in southern China, East Asia, and Southeast Asia.",
                    "Broccoli is an edible green plant in the cabbage family whose large flowering head, stalk and small associated leaves are eaten as a vegetable. Broccoli is classified in the Italica cultivar group of the species Brassica oleracea.",
                    "Cabbage is a leafy green, red, or white biennial plant grown as an annual vegetable crop for its dense-leaved heads. It is descended from the wild cabbage, and belongs to the cole crops or brassicas, meaning it is closely related to broccoli and cauliflower; Brussels sprouts; and Savoy cabbage.",
                    "The carrot is a root vegetable, usually orange in color, though purple, black, red, white, and yellow cultivars exist. They are a domesticated form of the wild carrot, Daucus carota, native to Europe and Southwestern Asia. The plant probably originated in Persia and was originally cultivated for its leaves and seeds.",
                    "Cauliflower is one of several vegetables in the species Brassica oleracea in the genus Brassica, which is in the Brassicaceae family. It is an annual plant that reproduces by seed. Typically, only the head is eaten – the edible white flesh sometimes called curd",
                    "A cherry is the fruit of many plants of the genus Prunus, and is a fleshy drupe. Commercial cherries are obtained from cultivars of several species, such as the sweet Prunus avium and the sour Prunus cerasus.",
                    "The chili pepper, from Nahuatl chīlli, is the berry-fruit of plants from the genus Capsicum which are members of the nightshade family, Solanaceae. Chili peppers are widely used in many cuisines as a spice to add pungent 'heat' to dishes",
                    "Coconut flesh is highly nutritious and rich in fibre, vitamins C, E, B1, B3, B5 and B6 and minerals including iron, selenium, sodium, calcium, magnesium and phosphorous.",
                    "Corn is a starchy vegetable and cereal grain that has been eaten all over the world for centuries. It's rich in fiber, vitamins and minerals. However, the health benefits of corn are controversial — while it contains beneficial nutrients, it can also spike blood sugar levels.",
                    "Cucumber is a widely-cultivated creeping vine plant in the Cucurbitaceae gourd family that bears cucumiform fruits, which are used as vegetables. There are three main varieties of cucumber—slicing, pickling, and burpless/seedless—within which several cultivars have been created",
                    "A pitaya or pitahaya is the fruit of several different cactus species indigenous to the Americas. Pitaya usually refers to fruit of the genus Stenocereus, while pitahaya or dragon fruit refers to fruit of the genus Selenicereus, both in the family Cactaceae.",
                    "The durian is the fruit of several tree species belonging to the genus Durio. There are 30 recognised Durio species, at least nine of which produce edible fruit, with over 300 named varieties in Thailand and 100 in Malaysia, as of 1987.",
                    "Eggplant, aubergine or brinjal is a plant species in the nightshade family Solanaceae. Solanum melongena is grown worldwide for its edible fruit. Most commonly purple, the spongy, absorbent fruit is used in several cuisines. Typically used as a vegetable in cooking, it is a berry by botanical definition.",
                    "Ficus carica is an Asian species of flowering plant in the mulberry family, known as the common fig. The fruit, also called the fig, is an important crop in those areas where it is grown commercially",
                    "Garlic is a species in the onion genus, Allium. Its close relatives include the onion, shallot, leek, chive, Welsh onion and Chinese onion. It is native to Central Asia and northeastern Iran and has long been a common seasoning worldwide, with a history of several thousand years of human consumption and use. ",
                    "Ginger is a flowering plant whose rhizome, ginger root or ginger, is widely used as a spice and a folk medicine. It is a herbaceous perennial which grows annual pseudostems about one meter tall bearing narrow leaf blades",
                    "Ginkgo biloba, or maidenhair, is a tree native to China that has been grown for thousands of years for a variety of uses.\nBecause it’s the only surviving member of an ancient order of plants, it’s sometimes referred to as a living fossil.\nWhile its leaves and seeds are often used in traditional Chinese medicine, modern research primarily focuses on ginkgo extract, which is made from the leaves.\nGinkgo supplements are associated with several health claims and uses, most of which focus on brain function and blood circulation.",
                    "A grape is a fruit, botanically a berry, of the deciduous woody vines of the flowering plant genus Vitis. Grapes can be eaten fresh as table grapes or they can be used for making wine, jam, grape juice, jelly, grape seed extract, raisins, vinegar, and grape seed oil.",
                    "Guava is a common tropical fruit cultivated in many tropical and subtropical regions. Psidium guajava is a small tree in the myrtle family, native to Mexico, Central America, the Caribbean and northern South America.",
                    "Kale, or leaf cabbage, belongs to a group of cabbage cultivars grown for their edible leaves, although some are used as ornamentals. Kale plants have green or purple leaves, and the central leaves do not form a head.",
                    "Kiwifruit or Chinese gooseberry is the edible berry of several species of woody vines in the genus Actinidia. The most common cultivar group of kiwifruit is oval, about the size of a large hen's egg",
                    "The leek is a vegetable, a cultivar of Allium ampeloprasum, the broadleaf wild leek. The edible part of the plant is a bundle of leaf sheaths that is sometimes erroneously called a stem or stalk. The genus Allium also contains the onion, garlic, shallot, scallion, chive, and Chinese onion.",
                    "The lemon is a species of small evergreen tree in the flowering plant family Rutaceae, native to South Asia, primarily Northeast India. The tree's ellipsoidal yellow fruit is used for culinary and non-culinary purposes throughout the world, primarily for its juice, which has both culinary and cleaning uses. ",
                    "Lettuce is an annual plant of the daisy family, Asteraceae. It is most often grown as a leaf vegetable, but sometimes for its stem and seeds. Lettuce is most often used for salads, although it is also seen in other kinds of food, such as soups, sandwiches and wraps; it can also be grilled.",
                    "Macadamia is a genus of four species of trees indigenous to Australia, and constituting part of the plant family Proteaceae. They are native to northeastern New South Wales and central and southeastern Queensland specifically. Three species of the genus are commercially important for their fruit, the macadamia nut.",
                    "Mache lettuce is small to medium in size with delicate, elongated leaves that can grow up to fifteen centimeters in length. The bright green leaves are thin, pliable, and smooth with a spatulate shape and grow in a loose, rosette pattern of 6-8 leaves",
                    "A mango is an edible stone fruit produced by the tropical tree Mangifera indica which is believed to have originated from the region between northwestern Myanmar, Bangladesh, and northeastern India.",
                    "Milk is a nutrient-rich liquid food produced by the mammary glands of mammals. It is the primary source of nutrition for young mammals, including breastfed human infants before they are able to digest solid food",
                    "A mushroom or toadstool is the fleshy, spore-bearing fruiting body of a fungus, typically produced above ground, on soil, or on its food source.",
                    "Okra or Okro, Abelmoschus esculentus, known in many English-speaking countries as ladies' fingers or ochro, is a flowering plant in the mallow family. It is valued for its edible green seed pods. It is a good source of minerals, vitamins, antioxidants, and fiber.",
                    "The olive, known by the botanical name Olea europaea, meaning \"European olive\", is a species of small tree in the family Oleaceae, found traditionally in the Mediterranean Basin. ",
                    "The onion, also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium. The shallot is a botanical variety of the onion. Until 2010, the shallot was classified as a separate species.",
                    "The orange is the fruit of various citrus species in the family Rutaceae; it primarily refers to Citrus × sinensis, which is also called sweet orange, to distinguish it from the related Citrus × aurantium, referred to as bitter orange.",
                    "The papaya, papaw, or pawpaw is the plant Carica papaya, one of the 22 accepted species in the genus Carica of the family Caricaceae. Its origin is in the tropics of the Americas, perhaps from Central America and southern Mexico. ",
                    "Parsley or garden parsley is a species of flowering plant in the family Apiaceae that is native to the central and eastern Mediterranean region, but has been naturalized elsewhere in Europe, and is widely cultivated as an herb, and a vegetable. ",
                    "Passiflora edulis, commonly known as passion fruit, is a vine species of passion flower native to southern Brazil through Paraguay and northern Argentina. It is cultivated commercially in tropical and subtropical areas for its sweet, seedy fruit.",
                    "The peach is a deciduous tree native to the region of Northwest China between the Tarim Basin and the north slopes of the Kunlun Mountains, where it was first domesticated and cultivated. It bears edible juicy fruits with various characteristics, most called peaches and others, nectarines.",
                    "The peanut, also known as the groundnut, goober, pindar or monkey nut, and taxonomically classified as Arachis hypogaea, is a legume crop grown mainly for its edible seeds. It is widely grown in the tropics and subtropics, being important to both small and large commercial producers",
                    "Pears are fruits produced and consumed around the world, growing on a tree and harvested in late Summer into October. The pear tree and shrub are a species of genus Pyrus, in the family Rosaceae, bearing the pomaceous fruit of the same name.",
                    "The pea is most commonly the small spherical seed or the seed-pod of the pod fruit Pisum sativum. Each pod contains several peas, which can be green or yellow. Botanically, pea pods are fruit, since they contain seeds and develop from the ovary of a flower.",
                    "Black pepper is a flowering vine in the family Piperaceae, cultivated for its fruit, known as a peppercorn, which is usually dried and used as a spice and seasoning. When fresh and fully mature, the fruit is about 5 mm in diameter, dark red, and contains a single seed, like all drupes.",
                    "Pineapple with its botanical name Ananas comosus belongs to family Bromeliaceae possesses various health promoting properties. Pineapples are wide cylindrical in shape, have scaly green, yellow or brown skin and spiny blue to green leaves. The plant is tolerable to drought and grows upto 5 feet tall and bears fruit of 15 to 25 cm long with spiky and tough exterior. The fruit weighs upto 2.5 kg. It has sweet and tart taste. Pineapples are also known as Common Edible Pineapple, Ananas Bromeliad, Abarba, Ananas, Anana, Anaras, Andras, Anarash, Aneh, Apangdang, Annasi, Bonat, Bhuin kathar, Danas, Kanas, Ennanansi and Maneas.",
                    "A plum is a fruit of some species in Prunus subg. Prunus. Mature plum fruits may have a dusty-white waxy coating that gives them a glaucous appearance.",
                    "The pomegranate is a fruit-bearing deciduous shrub in the family Lythraceae, subfamily Punicoideae, that grows between 5 and 10 m tall. The pomegranate was originally described throughout the Mediterranean region",
                    "The potato is a root vegetable native to the Americas, a starchy tuber of the plant Solanum tuberosum, and the plant itself is a perennial in the nightshade family, Solanaceae. Wild potato species, originating in modern-day Peru, can be found throughout the Americas, from Canada to southern Chile.",
                    "A pumpkin is a cultivar of winter squash that is round with smooth, slightly ribbed skin, and is most often deep yellow to orange in coloration. The thick shell contains the seeds and pulp.",
                    "The radish is an edible root vegetable of the family Brassicaceae that was domesticated in Asia prior to Roman times. Radishes are grown and consumed throughout the world, being mostly eaten raw as a crunchy salad vegetable with a pungent flavor.",
                    "The raspberry is the edible fruit of a multitude of plant species in the genus Rubus of the rose family, most of which are in the subgenus Idaeobatus. The name also applies to these plants themselves. Raspberries are perennial with woody stems.",
                    "Spinach is a leafy green flowering plant native to central and western Asia. It is of the order Caryophyllales, family Amaranthaceae, subfamily Chenopodioideae. Its leaves are a common edible vegetable consumed either fresh, or after storage using preservation techniques by canning, freezing, or dehydration.",
                    "Carambola, also known as star fruit or starfruit, is the fruit of Averrhoa carambola, a species of tree native to tropical Southeast Asia. The fruit is commonly consumed in parts of Brazil, Southeast Asia, South Asia, the South Pacific, Micronesia, parts of East Asia, the United States, and the Caribbean.",
                    "The garden strawberry is a widely grown hybrid species of the genus Fragaria, collectively known as the strawberries, which are cultivated worldwide for their fruit. The fruit is widely appreciated for its characteristic aroma, bright red color, juicy texture, and sweetness.",
                    "The tomato is the edible berry of the plant Solanum lycopersicum, commonly known as a tomato plant. The species originated in western South America and Central America. The Nahuatl word tomatl gave rise to the Spanish word tomate, from which the English word tomato derived.",
                    "The turnip or white turnip is a root vegetable commonly grown in temperate climates worldwide for its white, fleshy taproot. The word turnip is a compound of turn as in turned/rounded on a lathe and neep, derived from Latin napus, the word for the plant.",
                    "A walnut is the nut of any tree of the genus Juglans, particularly the Persian or English walnut, Juglans regia. A walnut is the edible seed of a drupe, and thus not a true botanical nut. It is commonly consumed as a nut. ",
                    "Watercress or yellowcress is a species of aquatic flowering plant in the cabbage family Brassicaceae. Its botanical name is Nasturtium officinale. Watercress is a rapidly growing, perennial plant native to Europe and Asia. It is one of the oldest known leaf vegetables consumed by humans",
                    "Watermelon is a flowering plant species of the Cucurbitaceae family. A scrambling and trailing vine-like plant, it was originally domesticated in Africa. It is a highly cultivated fruit worldwide, with more than 1,000 varieties. Wild watermelon seeds have been found in the prehistoric Libyan site of Uan Muhuggiag.",
            };

    String vegvitamins[] =
            {
                    "• Protein\n• Fibre\n• Calcium\n• Magnesium\n• Iron\n• Vitamin E\n• Riboflavin\n• Potassium\n• Niacin\n• Copper\n• Monounsaturated Fat(5) ",
                    "• Vitamin \n• Potassiu\n• Vitamin \n• Vitamin B\n• Manganes\n• Copper",
                    "• Vitamin \n• Vitamin \n• Pantothenic Acid\n• Vitamin \n• Beta-caroten\n• Potassiu\n• Lutei\n• Zeaxanthin",
                    "• Carbs\n• Fiber\n• Protein\n• Fat\n• Vitamin\n• Vitamin\n• Thiamine\n• Riboflavin\n• Niacin\n• Vitamin\n• Folate\n• Iron\n• Magnesium\n• Phosphorus\n• Potassium\n• Calcium\n• Zinc",
                    "• Calcium\n• Potassium\n• Folate\n• Vitamin C\n• Vitamin K\n• Vitamin A",
                    "• Folate.\n• Magnesium.\n• Potassium.\n• Riboflavin \n• Niacin \n• Pantothenic Acid \n• Pyridoxine \n• Vitamin C.",
                    "• Energy\n• Protein\n• Fat\n• Carbohydrate\n• Fibre\n• Calcium\n• Phosphorous\n• Iron\n• Copper\n• Potassium\n• Magnesium\n• Vitamin E",
                    "• Potassium\n• Vitamin B6\n• Vitamin C\n• Magnesium\n• Copper\n• Manganese\n• Net carbs\n• Fiber",
                    "• Iron\n• Magnesium\n• Manganese\n• Sodium\n• Zinc\n• Copper\n• Selenium",
                    "• Calories\n• Water\n• Protein\n• Carbs\n• Sugar\n• Fiber\n• Fat\n• Vitamin C\n• Vitamin B6\n• Vitamin K1\n• Potassium\n• Folate\n• Vitamin E\n• Vitamin A\n• Capsanthin\n• Violaxanthin\n• Lutein\n• Quercetin\n• Luteolin",
                    "• Calories\n• Protein\n• Total fat\n• Total carbs\n• Total sugar\n• Fiber\n• Calcium\n• Iron\n• Magnesium\n• Phosphorus\n• Potassium\n• Zinc\n• Manganese\n• Selenium\n• Vitamin C\n• Folate\n• Vitamin A\n• Vitamin K",
                    "• Carbs\n• Protein\n• Fat\n• Fiber\n• Vitamin C\n• Vitamin A\n• Vitamin K\n• Vitamin B9 (Folate)\n• Potassium\n• Phosphorus\n• Selenium",
                    "• Calories\n• Protein\n• Fiber\n• Vitamin K\n• Vitamin C\n• Folate\n• Manganese\n• Vitamin B6",
                    "• Biotin\n• Potassium\n• Vitamins A \n• Vitamins K1 \n• Vitamins B6",
                    "• Calories\n• Protein\n• Fiber\n• Vitamin K\n• Vitamin C\n• Folate\n• Manganese\n• Vitamin B6",
                    "• Fibre\n• Potassium\n• Calcium\n• Vitamin A\n• Folic acid\n• Antioxidant",
                    "• Vitamin E\n• Iron\n• Vitamin A\n• Sodium\n• Vitamin B6 (Pyridoxine)\n• Copper\n• Total dietary Fiber\n• Vitamin K\n• Manganese\n• Vitamin B3 (Niacin)",
                    "• Coconut flesh is highly nutritious and rich in fibre\n• Vitamins C\n• Vitamins E\n• Vitamins B1\n• Vitamins B3\n• Vitamins B5 \n• Vitamins B6\n• Iron\n• Selenium\n• Sodium\n• Calcium\n• Magnesium \n• Phosphorous.",
                    "• Vitamins B\n• Zinc\n• Magnesium\n• Copper\n• Iron\n• Manganese\n• Antioxidants carotenoids\n• Lutein\n• Zeaxanthin",
                    "• Calories\n• Total fat\n• Carbs\n• Protein\n• Fiber\n• Vitamin C\n• Vitamin K\n• Magnesium\n• Potassium\n• Manganese",
                    "• Calories\n• Protein\n• Fat\n• Carbs\n• Fiber\n• Vitamin C\n• Iron\n• Magnesium",
                    "• Calories\n• Fat\n• Carbs\n• Fiber\n• Protein\n• Vitamin C\n• Thiamine\n• Manganese\n• Vitamin B6\n• Potassium\n• Riboflavin\n• Copper\n• Folate\n• Magnesium\n• Niacin",
                    "• Calories\n• Carbs\n• Fiber\n• Protein\n• Manganese\n• Folate\n• Potassium\n• Vitamin K\n• Vitamin C",
                    "• Calories\n• Protein\n• Fat\n• Carbs\n• Fiber\n• Copper\n• Magnesium\n• Potassium\n• Riboflavin\n• Thiamine\n• Vitamin B6\n• Vitamin K",
                    "• Manganese\n• Vitamin B6\n• Vitamin C\n• Selenium\n• Fiber\n• Calcium\n• Copper\n• Potassium\n• Phosphorus\n• Iron\n• Vitamin B1",
                    "• Antioxidants",
                    "• Calcium\n• Vitamin B3\n• iron\n• magnesium\n• Vitamin E\n• Vitamin B1\n• B6\n• B2\n• Vitamin A\n• copper\n• manganese\n• zinc\n• folic acid\n• Vitamin B8\n• iodine\n• Vitamin D\n• Vitamin B12.",
                    "• Protein\n• Fat\n• Carbohydrate\n• Fiber\n• Potassium\n• Iron\n• Magnesium\n• Phosphorus\n• Sodium\n• Zinc\n• Vitamin C\n• Folate\n• Vitamins C\n• Vitamins K",
                    "• Carbohydrates\n• Sugars\n• Fat\n• Dietary fiber\n• Potassium\n• Vitamin C\n• Vitamin A",
                    "• Vitamin A\n• Vitamin K\n• Vitamin C\n• Vitamin B6\n• Manganese\n• Calcium\n• Copper\n• Potassium\n• Magnesium",
                    "• Carbohydrates \n• Fiber \n• Calcium \n• Magnesium \n• Phosphorus \n• Potassium \n• Copper \n• Vitamin C \n• Folate \n• Beta carotene \n• Lutein & zeaxanthin \n• Vitamin E \n• Vitamin K ",
                    "• Vitamin K\n• Iron\n• Manganese\n• Vitamin B6\n• Vitamin B9",
                    "• Carbohydrates\n• Calcium\n• Iron\n• Magnesium\n• Phosphorus\n• Potassium\n• Selenium\n• Vitamin C\n• Folate\n• Choline\n• Vitamin A\n• Lutein\n• Zeaxanthin",
                    "• Vitamin A\n• Magnesium\n• Folate\n• Calcium\n• Vitamin C\n• Vitamin K",
                    "• Calories\n• Fat\n• Protein\n• Carbs\n• Sugar\n• Fiber\n• Manganese\n• Thiamine\n• Copper\n• Magnesium\n• Iron\n• Vitamin B6",
                    "• Vitamin A\n• Vitamin C (Ascorbic acid\n• Iron\n• Vitamin B6 (Pyridoxine)\n• Manganese",
                    "• Calories\n• Protein\n• Carbs\n• Fat\n• Dietary fiber\n• Vitamin C\n• Copper\n• Folate\n• Vitamin B6\n• Vitamin A\n• Vitamin E\n• Vitamin B5\n• Vitamin K\n• Niacin\n• Potassium\n• Riboflavin\n• Manganese\n• Thiamine\n• Magnesium",
                    "• Calories\n• Water\n• Protein\n• Carbs\n• Sugar\n• Fiber\n• Fat",
                    "• Carbohydrate \n• Calcium \n• Iron \n• Magnesium \n• Phosphorus \n• Potassium \n• Sodium \n• Zinc \n• Copper \n• Selenium \n• Vitamin C \n• Vitamin D \n• Folate \n• Choline \n• Niacin ",
                    "• Calories\n• Carbs\n• Protein\n• Fat\n• Fiber\n• Magnesium\n• Folate\n• Vitamin A\n• Vitamin C\n• Vitamin K\n• Vitamin B6",
                    "• Calories\n• Water\n• Protein\n• Carbs\n• Sugar\n• Fiber\n• Fat\n• Saturated\n• Monounsaturated\n• Polyunsaturated",
                    "• Vitamin C \n• Vitamin B-6 \n• Manganese \n• Onions also contain small amounts of\n• Calcium\n• Iron\n• Folate\n• Magnesium\n• Phosphorus\n• Potassium\n• The antioxidants quercetin and sulfur",
                    "• Vitamin C    \n• Thiamin \n• Folate  \n• Fiber   At least \n• Calcium    Between \n• Potassium\n• Fat\n• Potassium\n• Carbohydrate\n• Sugar\n• Protein",
                    "• Calories\n• Carbohydrate\n• Protein\n• Folate\n• Vitamin A\n• Magnesium\n• Copper\n• Pantothenic acid\n• Fiber\n• B vitamins\n• Alpha and beta-carotene\n• Lutein and zeaxanthin\n• Vitamin E\n• Calcium\n• Potassium\n• Vitamin K\n• Lycopene",
                    "• Iron\n• Calcium\n• Total dietary Fiber\n• Potassium\n• Manganese",
                    "• Calories\n• Fiber\n• Vitamin C\n• Vitamin A\n• Iron\n• Potassium",
                    "• Calories\n• Protein\n• Fat\n• Cholesterol and sodium\n• Carbohydrate\n• Sugar\n• Fiber\n• Vitamins A\n• Vitamins E\n• Vitamins K",
                    "• Calories\n• Water\n• Protein\n• Carbs\n• Sugar\n• Fiber\n• Fat\n• Saturated\n• Monounsaturated\n• Polyunsaturated\n• Omega-3\n• Omega-6\n• Trans",
                    "• Calories\n• Fat\n• Carbohydrate\n• Sugar  \n• Fiber\n• Protein\n• Vitamin C\n• Vitamin K\n• Potassium\n• Calcium\n• Iron\n• Magnesium\n• Riboflavin\n• Vitamin B-6\n• Folate",
                    "• Vitamin C \n• Vitamin B1 \n• Vitamin K \n• Copper\n• Iron\n• Manganese\n• Vitamin B9 \n• Phosphorus\n• Total dietary Fiber \n• Vitamin B3 \n• Vitamin B6 \n• Isoleucine \n• Threonine \n• Zinc\n• Valine \n• Carbohydrate \n• Protein \n• Vitamin B2 \n• Lysine \n• Leucine \n• Histidine \n• Tryptophan \n• Magnesium",
                    "• Calories\n• Water\n• Protein\n• Carbs\n• Sugar\n• Fiber\n• Fat",
                    "• Vitamin C \n• Manganese \n• Copper \n• Carbohydrate \n• Vitamin B6 ",
                    "• Carbohydrate \n• Fiber   \n• Protein \n• Iron    \n• Potassium   \n• Magnesium   \n• Manganese   \n• Phosphorus  \n• Copper  \n• Zinc    \n• Niacin  \n• Pantothenic acid    \n• Riboflavin  \n• Thiamine    \n• Vitamin A   \n• Vitamin C   \n• Vitamin B6  \n• Vitamin E   \n• Vitamin K",
                    "• Copper\n• Carbohydrate \n• Vitamin K \n• Vitamin C \n• Total dietary Fiber\n• Vitamin B9 \n• Vitamin B5 \n• Vitamin B6 \n• Vitamin B1 \n• Phosphorus",
                    "• Vitamin B6 \n• Carbohydrate \n• Iron \n• Copper \n• Potassium ",
                    "• Iron \n• Vitamin B6 \n• Manganese \n• Phosphorus \n• Copper ",
                    "• Vitamin C \n• Copper\n• Vitamin B9 \n• Iron\n• Potassium\n• Total dietary Fiber\n• Magnesium\n• Vitamin B6 ",
                    "• Calories\n• Carbs\n• Fiber\n• Protein\n• Fat\n• Vitamin C\n• Manganese\n• Vitamin K\n• Vitamin E\n• B vitamins\n• Iron\n• Magnesium\n• Phosphorus\n• Potassium\n• Copper",
                    "• Vitamin C \n• Vitamin A\n• Vitamin B9 \n• Calcium\n• Iron\n• Manganese\n• Vitamin B6 \n• Potassium\n• Copper\n• Total dietary Fiber",
                    "• Water \n• Energy\n• Protein \n• Total Fat \n• Ash \n• Carbohydrate \n• Total dietary Fiber\n• Total Sugars \n• Copper\n• Potassium\n• Magnesium\n• Phosphorus\n• Manganese\n• Zinc\n• Iron\n• Selenium\n• Calcium\n• Sodium\n• Vitamin C \n• Vitamin B1 \n• Vitamin B2 \n• Vitamin B3 \n• Vitamin B5 \n• Vitamin B6 \n• Vitamin B9 \n• Choline\n• Vitamin A \n• Beta Carotene \n• Alpha Carotene  \n• Lutein\n• Zeaxanthin \n• Vitamin E \n• Total saturated fat \n• Palmitic acid \n• Stearic acid \n• Oleic acid \n• Linoleic acid \n• Linolenic acid \n• Tryptophan \n• Threonine \n• Isoleucine \n• Leucine \n• Lysine    \n• Methionine \n• Phenylalanine and Tyrosine \n• Valine \n• Histidine \n• Arginine \n• Alanine  \n• Aspartic acid \n• Glutamic acid \n• Glycine \n• Proline \n• Serine ",
                    "• Calories\n• Water\n• Protein\n• Carbs\n• Sugar\n• Fiber\n• Fat",
                    "• Calories\n• Water\n• Protein\n• Carbs\n• Sugar\n• Fiber\n• Fat",
                    "• Vitamin C \n• Copper\n• Vitamin B6 \n• Manganese\n• Carbohydrate\n• Total dietary Fiber\n• Sodium\n• Potassium\n• Vitamin B5 \n• Phosphorus",
                    "• Manganese\n• Copper\n• Phosphorus\n• Tryptophan \n• Valine \n• Isoleucine \n• Histidine \n• Protein 3\n• Magnesium\n• Leucine \n• Vitamin B6 (Pyridoxine) \n• Threonine \n• Iron\n• Vitamin B5 (Pantothenic acid) \n• Selenium\n• Zinc\n• Lysine \n• Total dietary Fiber \n• Vitamin E (alpha-tocopherol) \n• Potassium\n• Vitamin B2 (Riboflavin) ",
                    "• Calories\n• Carbs\n• Protein\n• Fat\n• Fiber\n• Vitamin A\n• Vitamin C\n• Vitamin K\n• Calcium\n• Manganese",
                    "• Calories\n• Water\n• Protein\n• Carbs\n• Sugar\n• Fiber\n• Fat\n• Vitamin C\n• Potassium\n• Copper\n• Vitamin B5\n• Vitamin A",
            };

    String vegprevents[] =
            {
                    "• Reduces Cholesterol\n• Reduces blood pressure\n• Reduces risks of developing Alzheimer’s disease\n• Reduces risks of developing prostate cancer\n• Reduces Weight\n• Reduces risks of Anemia",
                    "• Apples May Be Good for Weight Loss\n• Apples May Be Good for Your Heart\n• They're Linked to a Lower Risk of Diabetes\n• TheyMay Have Prebiotic Effects and Promote Good Gut Bacteria\n• Substances in Apples May Help Prevent Cancer\n• Apples Contain Compounds That Can Help Fight Asthma.",
                    "• Very nutritious and low in calories. Apricots are very nutritious and contain many essential vitamins and minerals \n• High inantioxidants \n• May promote eye health \n• May boost skin health \n• May promote gut health \n• High in potassium \n• Veryhydrating \n• May protect your liver",
                    "• Loaded With Nutrients\n• May Lower 'Bad' LDL Cholesterol and Increase 'Good' HDL Cholesterol\n• May Help Regulate Blood Pressure\n• May Improve Liver Health\n• May Improve Digestive Health\n• May Ease Symptoms of Irritable Bowel Syndrome\n• May Help Lower Blood Sugar\n• May Have Anticancer Effects",
                    "• Calcium, which helps the blood to clot normally\n• Potassium, a mineral and an electrolyte that's vital for heart and nerve function\n• Folate, a B vitamin\n• Vitamin C, a powerful antioxidant that helps support the immune system\n• Vitamin K, which helps with blood coagulation",
                    "• Avocado Is Incredibly Nutritious\n• They Contain More Potassium Than Bananas\n• Avocado Is Loaded With Heart-Healthy Monounsaturated Fatty Acids\n• Avocados Are Loaded With Fiber\n• Eating Avocados Can Lower Cholesterol and Triglyceride Levels\n• People Who Eat Avocados Tend to Be Healthier",
                    "• Keeps Infections At Bay\n• Supports Menstrual Wellness\n• Controls Diabetes\n• Boosts Mood And Reduces Anxiety\n• Averts Cancer And heart Disease\n• Improves Lactation\n• Slows The Ageing Process \n• Promotes Kidney Function\n• Boosts Iron Levels\n• Remedies Digestive Problems\n• Curing the infection\n• Overcoming diabetes and anemia\n• Improves lactation, Reduce Free Radical Activity,\n• Menstrual problems and weight loss\n• Boost Mood and Reduce Anxiety\n• Anti-ageing power\n• Gastrointestinal health",
                    "• Bananas Contain Many Important Nutrients\n• Bananas Contain Nutrients That Moderate Blood Sugar Levels\n• Bananas May Improve Digestive Health\n• Bananas May Aid Weight Loss\n• Bananas May Support Heart Health\n• Bananas Contain Powerful Antioxidants\n• Bananas May Help You Feel More Full\n• Unripe Bananas May Improve Insulin Sensitivity.",
                    "• Helps lower blood pressure. Beet juice may help lower your blood pressure\n• Improves exercise stamina\n• May improve muscle power in people with heart failure\n• May slow the progression of dementia\n• Helps you maintain a healthy weight\n• May prevent cancer\n• Good source of potassium\n• Good source of other minerals",
                    "• Eye health\n• Anemia prevention",
                    "• Aids in the Prevention of Cancer. Studies show that cruciferous vegetables such as bok choy help to reduce your risk of \n• developing cancer\n• Fights Inflammation. Like other dark, leafy greens, bok choy is an excellent source of the flavonoid quercetin\n• Lowers the Risk of Heart Disease.",
                    "• Packed With Vitamins, Minerals and Bioactive Compounds\n• Contains Potent Antioxidants That Offer Health-Protective Effects\n• Bioactive Compounds May Contribute to Reduced Inflammation\n• May Protect Against Certain Types of Cancer\n• Antioxidants and Fiber May Aid Blood Sugar Control\n• May Support Heart Health in a Variety of Ways\n• Promotes Healthy Digestion and Reduced Constipation\n• May Slow Mental Decline and Support Healthy Brain Function\n• May Help Slow the Aging Process\n• Vitamin C Content Supports a Healthy Immune System\n• May Support Dental and Oral Health\n• May Promote Healthy Bones and Joints\n• Nutrient Content May Support a Healthy Pregnancy\n• May Protect Your Skin From Sun Damage",
                    "• Cabbage Is Packed With Nutrients. Share on Pinterest\n• It May Help Keep Inflammation in Check\n• Cabbage Is Packed With Vitamin C\n• It Helps Improve Digestion\n• May Help Keep Your Heart Healthy\n• May Lower Blood Pressure\n• Could Help Lower Cholesterol Levels\n• Cabbage Is an Excellent Source of Vitamin K.",
                    "• Reduced risk of cancer\n• Lower blood cholesterol\n• Helps in Weight loss\n• Reduced risk of night blindness",
                    "• A source of antioxidants. Cauliflower is a heart-friendly vegetable thanks to a plant compound called sulforaphane\n• High in choline\n• Rich in sulforaphane\n• May support hormonal balance\n• May support the immune system.",
                    "• Packed with nutrients\n• Rich in antioxidants and anti-inflammatory compounds\n• Can boost exercise recovery\n• May benefit heart health\n• May improve symptoms of arthritis and gout\n• May improve sleep quality\n• Easy to add to your diet.",
                    "• Reduced inflammation. Chilli peppers contain a substance called capsaicin, which gives peppers their characteristic pungency, \n• producing mild to intense spice when eaten\n• Natural pain relief\n• Cardiovascular benefits\n• Clear congestion\n• Boost immunity\n• Lose weight",
                    "• May boost heart health\n• May support weight loss\n• May aid digestive health\n• May stabilize blood sugar\n• May improve immunity\n• May benefit your brain\n• Aid people with impaired memory or brain function, such as those with Alzheimer’s disease",
                    "• Improves Eye health\n• Prevention of diverticular disease",
                    "• It's High in Nutrients. Cucumbers are low in calories but high in many important vitamins and minerals\n• It Contains Antioxidants\n• It Promotes Hydration\n• It May Aid in Weight Loss\n• It May Lower Blood Sugar\n• It Could Promote Regularity\n• Easy to Add to Your Diet",
                    "• It's rich in antioxidants like flavonoids, phenolic acid, and betacyanin\n• It's naturally fat-free and high in fiber\n• It may help lower your blood sugar\n• It contains prebiotics, which are foods that feed the healthy bacteria called probiotics in your gut\n• It can strengthen your immune system.",
                    "• Like chocolate, durian can make you happy. Durian contains the amino acid tryptophan\n• Durian may help regulate blood pressure\n• Durian may help you sleep better\n• Durian may help combat skin pigmentation and wrinkles\n• Durian contains nutrients that may help support bone health\n• Durian boosts energy.",
                    "• A great source of vitamins & minerals. the vitamin & mineral content of eggplants is quite extensive\n• Helps with digestion\n• Improves heart health\n• Prevents cancer\n• Improves bone health\n• Prevents anemia\n• Increases brain function.",
                    "• Promote digestive health\n• May improve vascular and heart health\n• Decreased blood pressure\n• May help manage blood sugar levels\n• Potential anticancer properties",
                    "• Garlic Contains Compounds With Potent Medicinal Properties\n• Garlic Is Highly Nutritious But Has Very Few Calories\n• Garlic Can Combat Sickness, Including the Common Cold\n• The Active Compounds in Garlic Can Reduce Blood Pressure\n• Garlic Improves Cholesterol Levels, Which May Lower the Risk of Heart Disease.",
                    "• Keeps Your Mouth Healthy. Ginger's antibacterial power may also brighten your smile\n• Calms Nausea\n• Soothes Sore Muscles\n• Eases Arthritis Symptoms\n• Curbs Cancer Growth\n• Lowers Blood Sugar\n• Eases Period Pains.",
                    "• Contains Powerful Antioxidants\n• Can Help Fight Inflammation\n• Improves Circulation and Heart Health\n• Reduces Symptoms of Psychiatric Disorders and Dementia\n• Improves Brain Function and Well-Being\n• Can Reduce Anxiety\n• Can Treat Depression\n• Can Support Vision and Eye Health",
                    "• High Antioxidant Contents May Prevent Chronic Diseases\n• Plant Compounds May Protect Against Certain Types of Cancer\n• Beneficial for Heart Health in Various Impressive Ways\n• May Decrease Blood Sugar Levels and Protect Against Diabetes.",
                    "• May Help Lower Blood Sugar Levels\n• May Boost Heart Health\n• May Help Relieve Painful Symptoms of Menstruation\n• May Benefit Your Digestive System\n• May Aid Weight Loss\n• May Have an Anticancer Effect\n• May Help Boost Your Immunity\n• Eating Guavas May Be Good for Your Skin.",
                    "• Kale Is Among The Most Nutrient-Dense Foods on The Planet\n• Kale Is Loaded With Powerful Antioxidants Like Quercetin and Kaempferol\n• It Is an Excellent Source of Vitamin C\n• Kale Can Help Lower Cholesterol, Which May Reduce The Risk of Heart Disease\n• Kale Is One of The World's Best Sources of Vitamin K",
                    "• Kiwi Prevents Blood Clotting\n• Kiwi Can Help Asthma\n• Kiwi Improves Digestion\n• Helps Regulate Blood Pressure\n• Supports Immune Function\n• Reduces DNA Damage\n• Prevents Vision Loss\n• Inflammation when consumed regularly\n• Prevent it from leading to other diseases such as heart disease and stroke.\n• Improves Skin Health",
                    "• Contain a variety of nutrients\n• Packed with beneficial plant compounds\n• May reduce inflammation and promote heart health\n• May aid weight loss\n• May protect against certain cancers\n• May promote healthy digestion\n• Easy to add to your diet\n• Prevent cancer\n• Prevent heart ailments\n• Healthy pregnancy\n• Cholesterol levels",
                    "• Relieves a sore throat\n• Cancer-fighting benefits\n• Prevents kidney stones\n• Aids in digestion\n• Helps blood sugar\n• Promotes weight loss\n• Helps clear skin.",
                    "• High in nutrients but low in calories\n• Very hydrating\n• Loaded with powerful antioxidants\n• May keep your heart healthy\n• Excellent source of vitamin A\n• Packed with vitamin K\n• May help lower blood pressure\n• May promote weight loss.",
                    "• Rich in nutrients. Macadamia nuts are calorie-rich nuts that are high in healthy fats, vitamins, and minerals\n• Loaded with antioxidants\n• May boost heart health\n• May reduce your risk of metabolic syndrome\n• May aid weight loss\n• May improve gut health\n• Easy to add to your diet",
                    "• Reduces the risk of Cancer\n• Reduces the risk of Diarrhea\n• Increasing menstrual flow\n• Reduces the risk of Intestinal gas\n• Reduces the risk of Kidney disease\n• Producing hallucinations\n• Reduces the risk of Stomach problems",
                    "• Produce more disease-fighting white blood cells\n• Help these cells work more effectively and improve your skin’s defenses\n• Helps in hair growth\n• Polyphenols reduced oxidative stress and stopped the growth or destroyed various cancer cells\n• Reduced inflammation, protected cells against oxidative stress and either stopped the growth of cancer cells or killed them",
                    "• Maintain skin health\n• Enhance immune system\n• Cholesterol control\n• Promote density of bones\n• Digestive health",
                    "• Mitigate the risk of developing serious health conditions, such as Alzheimer's, heart disease, cancer, and diabetes. They're also great sources of Selenium",
                    "• Rich in nutrients\n• Contains beneficial antioxidants\n• May lower heart disease risk\n• May have anticancer properties\n• May lower blood sugar\n• Beneficial for pregnant women\n• Easy to add to your diet",
                    "• Improved heart health\n• Antioxidant properties\n• Improved bone health\n• Cancer prevention",
                    "• Protects Against Cancer. Researchers have proven the benefits of this wonder bulb in protecting cancer due to the rich antioxidant profile\n• Improves The Bone Health\n• Promotes Gut Health\n• Lowers Cholesterol\n• Enhance Skin Glow\n• Onions Make Tomatoes Good for you\n• Remedies Hypertension\n• Manages Diabetes.",
                    "• Protects your cells from damage.\n• Helps your body make collagen, a protein that heals wounds and gives you smoother skin.\n• Makes it easier to absorb iron to fight anemia.\n• Boosts your immune system, your body's defense against germs.",
                    "• Delicious and Loaded With Nutrients\n• Reducing free radicals that contribute to cancer\n• Help prevent heart disease\n• Enhance the protective effects of “good” HDL cholesterol\n• Antioxidant rich fruits and vegetables like papaya help reduce inflammatory markers \n• Protect your skin and may help reduce these signs of aging \n• Measurable reduction in depth of facial wrinkles ",
                    "• Contains many important nutrients\n• Rich in antioxidants\n• Supports bone health\n• Contains cancer-fighting substances\n• Rich in nutrients that protect your eyes\n• May improve heart health\n• Parsley extract has antibacterial properties\n• Easy to add to your diet",
                    "• Vitamin C. Move over, oranges\n• Vitamin A. Passion fruit's pulp and crunchy seeds have 8% of the vitamin A you need every day\n• Fiber. Passion fruit has a lot of it\n• Nutrients. Passion fruit also gives your body calcium, magnesium, phosphorus, potassium, and folate.",
                    "• Packed With Nutrients and Antioxidants. Peaches are rich in many vitamins, minerals, and beneficial plant compounds\n• May Aid Digestion\n• May Improve Heart Health\n• May Protect Your Skin\n• May Prevent Certain Types of Cancer\n• May Reduce Allergy Symptoms\n• Widely Available and Easy to Add to Your Diet.",
                    "• Peanuts Provides Energy\n• Moongphali Good Proteins for Vegetarians\n• Peanuts are Good for Brain\n• Healthy Bone Structure\n• Peanuts Good for Skin\n• Good for Eyes\n• Fights Inflammation\n• Diabetic friendly",
                    "• Highly nutritious. Pears come in many different varieties\n• May promote gut health\n• Contain beneficial plant compounds\n• Have anti-inflammatory properties\n• May offer anticancer effects\n• Linked to a lower risk of diabetes\n• May boost heart health\n• May help you lose weight.",
                    "• Prevents anaemia and fatigue\n• Improves your bone health\n• Fights and Damages Diabetes\n• Prevents signs of ageing\n• Helps reduce depression\n• Improves your immunity\n• Heart health\n• Pregnancy and Birth Defects\n• Prevents stomach cancer\n• Restless Leg Syndrome\n• Curing Cataracts \n• Enhances Learning\n• Proper growth",
                    "• High in antioxidants. Free radicals are unstable molecules that can damage your cells\n• Has anti-inflammatory properties\n• May benefit your brain\n• May improve blood sugar control\n• May lower cholesterol levels\n• May have cancer-fighting properties\n• A versatile spice",
                    "• Lower inflammation\n• Prevents cancer\n• Enhance immunity\n• Lowers constipation\n• Blood pressure regulation",
                    "• Heart disease. Phytochemicals and nutrients in plums lower the inflammation that triggers heart disease.\n• Anxiety. A plum a day may keep anxiety away\n• Constipation Relief\n• High blood pressure and stroke\n• Rich in antioxidants\n• Reduce blood sugar\n• Bone health.",
                    "• Help Fight Arthritis and Joint Pain\n• Ageing\n• May Improve Exercise Performance\n• Help Improve Memory\n• Help Fight Bacterial and Fungal Infections\n• Diabetes\n• Help Treat Erectile Dysfunction\n• Dental Care\n• Lower Risk of Heart Disease\n• Anemia\n• Lower Blood Pressure\n• Relieve Stress\n• Help Fight Prostate Cancer\n• Impressive Anti-Inflammatory Effects",
                    "• Heart health\n• Cancer\n• Dysentery\n• Mouth and throat infection\n• Abdominal pain\n• Wounds and burns",
                    "• Promote the health of the heart\n• Immune System\n• Ensures Soft and Supple Skin\n• Fight against cancer\n• Reduce Symptoms of Rheumatoid Arthritis\n• Strengthen our bones\n• Alleviating PMS Syndrome\n• Prevent constipation\n• Helps Maintain Dental Health\n• Helps Prevent Premature Aging",
                    "• Decreased risk of heart disease\n• Cancers, diabetes, and neurodegenerative conditions\n• Help lower high blood pressure\n• Improve blood flow",
                    "• Builds immune system\n• Health of eyes\n• Blood pressure\n• Improves cardiovascular issues\n• Weight loss\n• Anti-cancer",
                    "• May block microbial growth\n• May promote skin and hair health\n• May alleviate pain\n• May slow cancer cell growth\n• May support heart health\n• Reduces inflammation\n• May help treat cold symptoms",
                    "• Antioxidant activity\n• Anti-microbial and antifungal activity\n• Antitumor activity\n• Antiulcer activity\n• Hypotensive activity\n• Hypocholesterolemic activity\n• Nephrotoxic effect\n• Analgesic\n• Hypoglycemic\n• Anthelmintic\n• Hypocholesterolaemic & Hypolipidemic activity",
                    "• Control Diabetes\n• Treats gastritis\n• Healthy heart\n• Prevent Cancer\n• Maintain Hydration\n• Regulate Blood Pressure\n• Eyes vitamin\n• Hepatitis\n• Aid Digestion\n• Detoxify the Body\n• Heal Sore Throat\n• Boost Immunity\n• Prevent Liver Damage\n• Prevent Premature Aging",
                    "• Tomatoes are the major dietary source of the antioxidant lycopene, which has been linked to many health benefits, including reduced risk of heart disease and cancer. They are also a great source of vitamin C, potassium, folate, and vitamin K\n• Helps to maintain healthful blood pressure\n• Reduce their risk of cardiovascular disease",
                    "• Treating diverticulosis\n• Circulation\n• Metabolic Effects\n• Immune System\n• Anti-inflammatory benefits\n• Heart Health\n• Bone Strength\n• Maintaining vision\n• Digestive Efficiency\n• Cancer Prevention",
                    "• Reduces the risk of Cancer\n• Reduces the risk of Antifungal Action\n• Beneficial for Hair\n• Expels Parasites\n• Helps with weight loss\n• Immune System Health\n• Improved Reproduction in Men\n• Digestive Health\n• Respiratory Conditions\n• Improves Heart Health\n• Improves Skin Health\n• For Blood Sugar or Diabetes\n• Improves sleep",
                    "• Packed with Nutrients, Particularly Vitamin K\n• High Antioxidant Content May Lower Your Risk of Chronic Diseases\n• Contains Compounds That May Prevent Certain Types of Cancer\n• Beneficial for Heart Health in Many Impressive Ways\n• Mineral and Vitamin K Contents Protect Against Osteoporosis",
                    "• May block microbial growth\n• May promote skin and hair health\n• May alleviate pain\n• May slow cancer cell growth\n• May support heart health\n• Reduces inflammation\n• May help treat cold symptoms",
            };



    ImageView vegimg;
    TextView vegtitlee, vegdescp, vegvita, vegprev;

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main5);
        getSupportActionBar().hide(); // hide the title bar
        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN); //enable full screen

        HashMap<String, Integer> pos = new HashMap<>();

        for(int i = 0 ; i < vegtitle.length; i++){
            pos.put(vegtitle[i],i);
        }

        String namee = getIntent().getStringExtra("foodname");
        Integer position = pos.get(namee);


        vegimg = (ImageView)findViewById(R.id.vegimg);
        vegtitlee = (TextView) findViewById(R.id.vegtitle);
        vegdescp = (TextView) findViewById(R.id.vegdesc);
        vegvita = (TextView) findViewById(R.id.vegvit);
        vegprev = (TextView) findViewById(R.id.vegprev);

        vegimg.setImageResource(vegimages[position]);
        vegtitlee.setText(vegtitle[position]);
        vegdescp.setText(vegdescription[position]);
        vegvita.setText(vegvitamins[position]);
        vegprev.setText(vegprevents[position]);
    }
}